[package]
name = "lda"
version = "0.1.1"
authors = ["Alexey Suslov <alexey.suslov@gmail.com>"]

[dependencies]
indexmap = "1.0"
ndarray = "0.11.0"
randomkit = "0.1"
fastapprox = "0.2.0"

[dev-dependencies]
regex = "1.0"
wikipedia = "0.3.1"
textplots = "0.2"

[profile.release]
codegen-units = 1
